name: CI

on:
  workflow_dispatch:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup ccache
        if: runner.os != 'Windows'
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ci-${{ runner.os }}-${{ github.ref }}
          max-size: 2G
          restore-keys: |
            ci-${{ runner.os }}-refs/heads/main
            ci-${{ runner.os }}-

      - name: Setup sccache (Windows)
        if: runner.os == 'Windows'
        uses: mozilla-actions/sccache-action@v0.0.6
        env:
          SCCACHE_GHA_ENABLED: "true"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7

      - name: Setup
        run: |
          uv venv
          uv pip install black==24.10.0 clang_format==11.0.1 cmake-format

      - name: Format Check
        run: make format-check

      - name: Windows set exclusions on path checking
        if: runner.os == 'Windows'
        run: |
          powershell.exe -Command "Add-MpPreference -ExclusionPath '${{ github.workspace }}'"

      - name: Build (Linux and Mac)
        if: runner.os != 'Windows'
        env:
          CMAKE_C_COMPILER_LAUNCHER: ccache
          CMAKE_CXX_COMPILER_LAUNCHER: ccache
          GEN: ninja
        run: |
          make release

      - name: Build (Windows)
        if: runner.os == 'Windows'
        env:
          CMAKE_C_COMPILER_LAUNCHER: sccache
          CMAKE_CXX_COMPILER_LAUNCHER: sccache
          GEN: ninja
        run: |
          make release
          sccache --show-stats

      - name: Test (Linux and Mac)
        if: runner.os != 'Windows'
        run: |
          make unittest_release

      - name: Test (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          build/release/test/unittest.exe
